<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://apache.org" xmlns:xsi="http://w3.org" xsi:schemaLocation="http://apache.org http://apache.org">

  	<modelVersion>4.0.0</modelVersion>

	<parent>
    	<groupId>org.springframework.boot</groupId>
    	<artifactId>spring-boot-starter-parent</artifactId>
    	<version>4.1.0</version> <!-- Versi GA Stabil Terbaru (Rilis Juni 2026) -->
	</parent>

  	<groupId>com.kratonsolution.belian</groupId>
 	<artifactId>belian-parent</artifactId>
  	<version>1.0.0</version>
  	<packaging>pom</packaging>

	<name>belian</name>

	<build>
		<plugins>
			<plugin>
	            <groupId>org.springframework.boot</groupId>
	            <artifactId>spring-boot-maven-plugin</artifactId>
	            <!-- This tells Spring Boot not to look for a main class -->
	            <configuration>
	                <skip>true</skip>
	            </configuration>
	        </plugin>
		</plugins>
	</build>
  	<dependencies>
	    <dependency>
	    	<groupId>org.springframework.boot</groupId>
	    	<artifactId>spring-boot-starter</artifactId>
		</dependency>
  	</dependencies>
  	<modules>
  		<module>belian-dashboard</module>
  		<module>belian-erp</module>
  		<module>belian-identity</module>
  		<module>belian-core</module>
  	</modules>
</project>

