server:
  port: 8585
  session:
    timeout: 86400

spring:
  application:
    name: BelianERP
    version: 1.0.1
    description: Belian ERP v-1.0.1
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/belian
    username: belian
    password: belian
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MariaDB103Dialect
      current_session_context_class: thread
      cache:
        use_second_level_cache: true
        use_query_cache: true
        region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  messages:
    basename: messages
    cache-seconds: 0
    encoding: UTF-8
    fallback-to-system-locale: false

logging:
  level:
    root: ERROR
    org:
      zkoss: OFF
      hibernate: DEBUG
      springframework: OFF
      springframework.web: OFF
      com:
        kratonsolution:
          belian: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka