server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:belian.p12
    key-store-password: b3l14n
    key-store-type: PKCS12
    key-alias: belian

spring:
  application:
    name: BelianERP
    version: 1.0.1

logging:
  level:
    root: ERROR
    org:
      springframework: INFO
      com:
        kratonsolution: INFO