server:
  port: 8584

spring:
  application:
    name: Belian User Management Backend
    version: v-2.0.1
  r2dbc:
    url: r2dbc:postgresql://belian:belian@127.0.0.1:5432/belian_security?currentSchema=belian_security
    pool:
      enabled: true
      initial-size: 1
      max-size: 50
      max-idle-time: 30m
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8581"

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

springdoc:
  api-docs:
    groups:
      enabled: true
