/**
 * 
 */
package com.kratonsolution.belian.security.dm;

/**
 * @author agungdodiperdana
 *
 */
public interface AccessGrantedFor
{
	String ROLE_MODULE_READ = "ROLE_MODULE_READ";
	
	String ROLE_MODULE_CREATE = "ROLE_MODULE_CREATE";
	
	String ROLE_MODULE_UPDATE = "ROLE_MODULE_UPDATE";
	
	String ROLE_MODULE_DELETE = "ROLE_MODULE_DELETE";

	String ROLE_MODULE_PRINT = "ROLE_MODULE_PRINT";
	
	String ROLE_GEOGRAPHIC_READ = "ROLE_GEOGRAPHIC_READ";
	
	String ROLE_GEOGRAPHIC_CREATE = "ROLE_GEOGRAPHIC_CREATE";
	
	String ROLE_GEOGRAPHIC_UPDATE = "ROLE_GEOGRAPHIC_UPDATE";
	
	String ROLE_GEOGRAPHIC_DELETE = "ROLE_GEOGRAPHIC_DELETE";
	
	String ROLE_GEOGRAPHIC_PRINT = "ROLE_GEOGRAPHIC_PRINT";
}
