server:
  port: 9000
  servlet:
    context-path:

spring:
  application:
    name: Belian Service Gateway
    version: 2.0.1
  cloud:
    gateway:
      routes:
        - id: AccessModuleID
          uri: http://127.0.0.1:9001
          predicates:
            - Path=/api/v2/access-module,/api/v2/access-module/**
        - id: Access-User
          uri: http://127.0.0.1:9002
          predicates:
            - Path=/api/v2/users,/api/v2/users/**,/api/v2/user/detail/{email}
        - id: Access-Role
          uri: http://127.0.0.1:9003
          predicates:
            - Path=/api/v2/access-role,/api/v2/access-role/**,/api/v2/access-role/detail/{name}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.r2dbc: INFO
