server:
  port: 9001

spring:
  application:
    name: User-data-service
    version: 1.0.1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/belian?useSSL=false
    username: belian
    password: belian
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      current_session_context_class: thread
      cache:
        use_second_level_cache: true
        use_query_cache: true
        region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka

