server:
  port: 8583

spring:
  application:
    name: Belian Access Role
    version: v-2.0.1
  r2dbc:
    url: r2dbc:postgresql://belian:belian@127.0.0.1:5432/belian_security?currentSchema=belian_security
    pool:
      enabled: true
      initial-size: 1
      max-size: 50
      max-idle-time: 30m

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    io.springfox: OFF
    com.kratonsolution.belian.security.access.role: INFO
    org.springframework.r2dbc: DEBUG

springdoc:
  api-docs:
    groups:
      enabled: true
