server:
  port: 9001

spring:
  application:
    name: Belian Access Module
    version: v-2.0.1
  r2dbc:
    url: r2dbc:postgresql://belian:belian@127.0.0.1:5432/belian_security
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 15m

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    com.kratonsolution.belian.security.access.module: DEBUG
    org.springframework.r2dbc: DEBUG