server:
  port: 8030

spring:
  application:
    name: belian-user-management-service
    version: v-2.0.1
  r2dbc:
    url: r2dbc:postgresql://belian:belian@127.0.0.1:5432/belian_security?currentSchema=belian_security
    pool:
      enabled: true
      initial-size: 1
      max-size: 50
      max-idle-time: 30m
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:8001"

logging:
  level:
    root: INFO
    org.springframework.web: OFF
    org.springframework.security: OFF
    org.springframework.security.oauth2: OFF
    com.kratonsolution.belian: DEBUG

springdoc:
  api-docs:
    groups:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
  instance:
    prefer-ip-address: true